services:
  db:
    image: postgres:15
    env_file:
      - .env1
    environment:
      POSTGRES_DB: granit_ural_ais
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    env_file:
      - .env1
    ports:
      - "5005:5005"
    environment:
      - FLASK_SECRET_KEY=development-secret-key
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=granit_ural_ais
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - APP_PORT=5005
      - FLASK_DEBUG=1
    depends_on:
      db:
        condition: service_healthy
